### ISSUE TITLE
System Access Violation Exception

### ISSUE THREAD

**Issue by cyberricou** [Corsinvest/cv4ab-api-dotnet#4]
when there is a network outage,

In Tag.cs

public ResultOperation Read()
..
var statusCode = NativeMethod.plc_tag_read(Handle, Controller.Timeout);

System Access Violation Exception in this line

Congratutation for this nice project !

**Comment by franklupo** [comment]
Hi,
How can I solve the problem?
Do you have any ideas?

Best regards

**Comment by cyberricou** [comment]
Sorry, the last version of plctag.dll (2.18) solve the problem.
Best regards
