### ISSUE TITLE
x64 vs x86 native library

### ISSUE THREAD

**Issue by RobertoPeters** [Corsinvest/cv4ab-api-dotnet#5]
Assumed was that the native library was 64 bits, but as it seems it is a 32 bits version (of Windows anyway). It would be nice if we got it to work for 64 bits application (like I have).
I ran your test project, but that project also fails at the first call of a native method (creating a tag)

**Comment by franklupo** [comment]
Hi,
Have you tried to compile the library from the original project "https://github.com/kyle-github/libplctag" and replace it?

Best regards

**Comment by RobertoPeters** [comment]
Hi,
No I haven't. But I was thinking that the nuget package (and this project anyway) should be fixed for all users.
I would rather like to use the nuget package instead of compiling it myself.

I know it is a 32 bits version, because if I change the project of this solution to 32 bits, it runs. When I use AnyCPU or x64 I get a bad image format exception. So, the DLL is clearly a 32 bits version (Windows)

- Robert

**Comment by franklupo** [comment]
Hi,
I'm creating a new version for nuget. I will release soon.
32/64 for windows and linux.

Best regards

**Comment by manujshanker** [comment]
Hi Frank,
Do you have any date in mind when you are planning to release 64 bit version? I am working on a project which is dependant on plctag.dll (64 bit) and am looking forward to the next release.

Best,
Manuj

**Comment by franklupo** [comment]
Hi, 
New version released.

**Comment by franklupo** [comment]
News?

**Comment by manujshanker** [comment]
Works! 
Thanks.
