### ISSUE TITLE
Read boolean

### ISSUE THREAD

**Issue by Malfhas** [Corsinvest/cv4ab-api-dotnet#6]
Hello,

Thanks for your amazing work on this project.
This library works very well but i have only 1 issue.

I need to read boolean tags on my ControlLogix but i don't know how to do that.

I hope this is possible.

**Comment by franklupo** [comment]
Hi,
the native library not read bool.  I using the int and read single byte.

Best regards

**Comment by Malfhas** [comment]
Thank you for your reply. I tried to read in INT but later I can not find the information with the right bit. Would you have a small example of reading to propose to me, it will be great.

Thank you again for your work.

**Comment by franklupo** [comment]
Hi,
using ValueManager.GetBit
> tag.ValueManager.GetBit(index);

**Comment by Malfhas** [comment]
I seem to have already tried this method.

I realize a reading of the tag in INT16 and then I come to read the bit with this last method.

Except that I can not have a value consistent with the reality of the state of my boolean variable.

On a ControlLogix, what bit should you read?

Thank you.

**Comment by franklupo** [comment]
I do not understand the issue.

**Comment by Malfhas** [comment]
Hi,

Sorry for my English I am French.

Here is my code, "Etape1.X" is a BOOL variable in my ControlLogix controller.

With this code, "Etape1Value.Tag.ValueManager.GetBit (1)" always returns me the value "TRUE" even when the value is "FALSE".

I can not really read my Boolean variable :/

Thank you in advance for your help.





```

                        var Etape1Var = grp.CreateTagInt32("Etape1.X");
                        if (Etape1Var.GetStatus() == StatusCodeOperation.ERR_READ)
                        {
                            Console.WriteLine("{0} : Erreur de lecture variable Etape1.X", DateTime.Now.ToString(new CultureInfo("fr-FR")), Color.Red);
                        }
                        else
                        {
                            var Etape1Value = Etape1Var.Read();
                            
                            Console.WriteLine("{0} : Lecture Etape1.X -> " + Etape1Value.Tag.ValueManager.GetBit(1), DateTime.Now.ToString(new CultureInfo("fr-FR")), Color.White);
                        }
```

**Comment by franklupo** [comment]
Hi,
the index start 0.

**Comment by Malfhas** [comment]
Thanks for your quick answer :o

I have already tried to read index 0, I still do not have the correct information, no change of state while in the PLC, I change the value to perform my tests. I really do not understand :/

**Comment by Malfhas** [comment]
I am really bad. It's my fault, I was wrong on the slot number of my CPU in the rack. It works well now. Thank you again for your help and your work on this project!
